site:
  title: Morphia Docs
  start_page: morphia::index.adoc

content:
  sources:
#    - url: https://github.com/MorphiaOrg/morphia-docs-new
#    - url: https://github.com/djencks/morphia-docs-new.git
    - url: ./../morphia-docs-new
      branches: javadoc
      start_path: docs

ui:
  bundle:
    url: node_modules/@djencks/javadoc-ui/build/javadoc-ui-bundle.zip
    snapshot: true
  supplemental_files: ./supplemental-ui

output:
  clean: true

runtime:
  fetch: true

extensions:
  - path: "@djencks/antora-javadoc"
    config:
      extract: body
      layout: javadoc

